language: python

python:
  - "2.7"
  - "3.3"

# Recommended by Travis support:
sudo: required

# Install dependencies:
install:
  - pip install flake8

# Run tests:
script:
  - flake8 . --max-line-length=81

notifications:
  email: false
