build: off
deploy: off
version: '{build}'
clone_depth: 3
shallow_clone: true
pull_requests:
  do_not_increment_build_number: true

environment:
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python36

install:
  - python -m pip install --upgrade pip
  - ps: Install-Product node ''
  - scripts\install.cmd %PYTHON%

test_script:
  - scripts\run_tests.cmd %PYTHON%
